### ISSUE TITLE
Uncaught TypeError: Cannot read property 'customEventsHandler' of undefined

### ISSUE THREAD

**Issue by mpetersen** [markushedvall/plantuml-viewer#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [plantuml-viewer](https://github.com/markushedvall/plantuml-viewer) package, v0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'customEventsHandler' of undefined

```
At /Users/XXX/.atom/packages/plantuml-viewer/node_modules/svg-pan-zoom/src/svg-pan-zoom.js:585

TypeError: Cannot read property 'customEventsHandler' of undefined
    at SvgPanZoom.destroy (/Users/mpeterse/.atom/packages/plantuml-viewer/node_modules/svg-pan-zoom/src/svg-pan-zoom.js:585:19)
    at Object.publicInstance.pi.destroy (/Users/mpeterse/.atom/packages/plantuml-viewer/node_modules/svg-pan-zoom/src/svg-pan-zoom.js:705:33)
    at Transform.<anonymous> (/Users/mpeterse/.atom/packages/plantuml-viewer/lib/plantuml-viewer-view.js:86:20)
    at emitNone (events.js:72:20)
    at Transform.emit (events.js:163:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:357:13)
```

### Commands

```
     -0:15.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:13.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.3.0 plantuml-viewer:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-pair, v2.0.5
highlight-selected, v0.10.1
language-dot, v1.6.0
language-plantuml, v0.1.1
minimap, v4.12.3
plantuml-viewer, v0.3.0

# Dev
No dev packages
```

**Comment by markushedvall** [comment]
Thank you for reporting this bug. It should be fixed in the latest release (0.4.0).

Please let me know if you're still having issues .

**Comment by mpetersen** [comment]
I'm still having issues. Typical workflow is:
- Open .puml file
- Split editor down (because I like to have the UML diagram below the .puml file
- In the bottom editor open the PlantUML viewer [ctrl-alt-P]
- Close the bottom editor, so you only have the PlantUML viewer in the bottom split view
- Now I get this error
- Work on the .puml file, everything is fine
- Close the PlantUML viewer and I get the error again

**Comment by mpetersen** [comment]
Update: even when I change the sequence, e.g.:

- Open .puml file
- ctrl-alt-P
- Split editor down
- move PlantUML viewer to bottom view
- Now I get this error

**Comment by mpetersen** [comment]
Thank you, no more issues! :-)

**Comment by romeupalos** [comment]
Hi! I'm still having this issue. 100% reproducible

1. Use the autocomplete function to create a Activity UML.
2. Note that preview stops working.
3. Close and open the preview windows some times.
4. Observe Atom showing the crash screen.

**Atom Version**: 1.8.0
**System**: Ubuntu 15.10
**Thrown From**: [plantuml-viewer](https://github.com/markushedvall/plantuml-viewer) package, v0.7.0


### Stack Trace

Uncaught TypeError: Cannot read property 'customEventsHandler' of undefined

```
At /home/romeupalos/.atom/packages/plantuml-viewer/node_modules/svg-pan-zoom/src/svg-pan-zoom.js:592

TypeError: Cannot read property 'customEventsHandler' of undefined
    at [object Object].SvgPanZoom.destroy (/home/romeupalos/.atom/packages/plantuml-viewer/node_modules/svg-pan-zoom/src/svg-pan-zoom.js:592:19)
    at Object.publicInstance.pi.destroy (/home/romeupalos/.atom/packages/plantuml-viewer/node_modules/svg-pan-zoom/src/svg-pan-zoom.js:714:33)
    at PlantumlViewerView.detached (/home/romeupalos/.atom/packages/plantuml-viewer/lib/plantuml-viewer-view.js:95:26)
    at space-pen-div.View.element.detached (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:167:63)
    at space-pen-div.CustomElementPrototype.detachedCallback (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:55:55)
    at atom-pane.PaneElement.itemRemoved (/usr/share/atom/resources/app.asar/src/pane-element.js:181:29)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app.asar/src/pane.js:568:20)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:637:16)
    at atom-tabs.TabBarView.onClick (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:688:17)
```

### Commands

```
     -0:42.9.0 core:delete (atom-text-editor.editor.is-focused)
     -0:38.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:36.3.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:36.1.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:34.4.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:34.4.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:33.7.0 core:delete (atom-text-editor.editor.is-focused)
     -0:29.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:28.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:27.7.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:24.8.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:23.4.0 core:delete (atom-text-editor.editor.is-focused)
     -0:11.7.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:11.6.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:08.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.2.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
atom-typescript, v10.1.15
language-cassandra-cql, v0.1.2
language-docker, v1.1.7
language-dot, v1.6.0
language-groovy, v0.6.0
language-lua, v0.9.11
language-markdown, v0.19.1
language-plantuml, v0.2.0
language-pug, v0.0.17
language-smali, v0.1.1
linter, v1.11.18
minimap, v4.24.4
plantuml-viewer, v0.7.0
pp-markdown, v0.0.2

# Dev
No dev packages
```
