### ISSUE TITLE
can't display Chinese.

### ISSUE THREAD

**Issue by readpan** [markushedvall/plantuml-viewer#27]
I'm from China. I wanna use your plugin to write Chinese.but it's not able to display the correct words. 

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.3
**Electron Version**: 1.3.6
**System**: Unknown Windows Version
**Thrown From**: [plantuml-viewer](https://github.com/markushedvall/plantuml-viewer) package, v0.7.1

### Stack Trace

Uncaught TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

```
At buffer.js:259

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:259:9)
    at Function.Buffer.from (buffer.js:96:10)
    at new Buffer (buffer.js:75:17)
    at PlantumlViewerEditor.getBuffer (C:\Users\SaiAo\.atom\packages\plantuml-viewer\lib\plantuml-viewer-editor.js:67:10)
    at status-bar.StatusBarView.storeActiveBuffer (C:\Users\SaiAo\AppData\Local\atom\app-1.12.3\resources\app.asar\node_modules\status-bar\lib\status-bar-view.js:115:109)
    at C:\Users\SaiAo\AppData\Local\atom\app-1.12.3\resources\app.asar\node_modules\status-bar\lib\status-bar-view.js:38:17
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\SaiAo\AppData\Local\atom\app-1.12.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\SaiAo\AppData\Local\atom\app-1.12.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at C:\Users\SaiAo\AppData\Local\atom\app-1.12.3\resources\app.asar\src\pane-container.js:348:27
    at Pane.module.exports.Pane.observeActiveItem (C:\Users\SaiAo\AppData\Local\atom\app-1.12.3\resources\app.asar\src\pane.js:229:7)
    at C:\Users\SaiAo\AppData\Local\atom\app-1.12.3\resources\app.asar\src\pane-container.js:346:42
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\SaiAo\AppData\Local\atom\app-1.12.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\SaiAo\AppData\Local\atom\app-1.12.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.setActivePane (C:\Users\SaiAo\AppData\Local\atom\app-1.12.3\resources\app.asar\src\pane-container.js:198:22)
    at Pane.module.exports.Pane.activate (C:\Users\SaiAo\AppData\Local\atom\app-1.12.3\resources\app.asar\src\pane.js:835:14)
    at Pane.module.exports.Pane.focus (C:\Users\SaiAo\AppData\Local\atom\app-1.12.3\resources\app.asar\src\pane.js:240:21)
    at atom-pane.<anonymous> (C:\Users\SaiAo\AppData\Local\atom\app-1.12.3\resources\app.asar\src\pane-element.js:50:23)
```

### Commands

```
  2x -0:25.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:23.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:20 editor:newline (atom-text-editor.editor.is-focused)
     -0:19.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:05.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:03.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "plantuml-preview"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.1.0 (active)
atom-beautify, v0.29.13 (active)
auto-encoding, v0.6.2 (active)
language-plantuml, v0.2.0 (active)
markdown-pdf, v1.5.0 (inactive)
markdown-preview-plus, v2.4.0 (active)
markdown-scroll-sync, v2.1.2 (active)
plantuml-preview, v0.12.1 (inactive)
plantuml-viewer, v0.7.1 (active)
tablr, v1.5.5 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by lazydeer** [comment]
I changed the plugin charset setting as UTF-8 that work perfect with chinese.
![image](https://cloud.githubusercontent.com/assets/5389326/23117227/a930b958-f789-11e6-9630-a3ae726876f2.png)

**Comment by readpan** [comment]
Thanks man.

2017-02-20 16:28 GMT+08:00 Sika <notifications@github.com>:

**Comment by RainFool** [comment]
@zakiso where this page is？I can't find it in Atom

**Comment by readpan** [comment]
Thanks !

2017-06-23 18:12 GMT+08:00 RainFool <notifications@github.com>:
