### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidStopChanging' of undefined

### ISSUE THREAD

**Issue by NaruAkitsuki** [markushedvall/plantuml-viewer#33]
**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package 0.206.3

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidStopChanging' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:46

TypeError: Cannot read property 'onDidStopChanging' of undefined
    at BufferSearch.setEditor (/app.asar/node_modules/find-and-replace/lib/buffer-search.js:46:48)
    at /app.asar/node_modules/find-and-replace/lib/find.js:49:36
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/pane-container.js:348:27
    at Pane.module.exports.Pane.observeActiveItem (/app.asar/src/pane.js:241:7)
    at /app.asar/src/pane-container.js:346:42
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.setActivePane (/app.asar/src/pane-container.js:198:22)
    at Pane.module.exports.Pane.activate (/app.asar/src/pane.js:850:14)
    at /packages/plantuml-viewer/lib/plantuml-viewer-view.js:43:48)
    at /packages/plantuml-viewer/node_modules/jquery/dist/jquery.js:4435:9)
    at /packages/plantuml-viewer/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -6:51.2.0 core:backspace (input.hidden-input)
     -6:50.1.0 core:save (input.hidden-input)
     -6:44.6.0 core:undo (input.hidden-input)
     -5:32 core:select-all (input.hidden-input)
     -5:31.6.0 core:cut (input.hidden-input)
     -5:27.1.0 core:paste (input.hidden-input)
     -5:19.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
 11x -3:24.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
language-plantuml 0.2.0 
plantuml-viewer 0.7.1 
Sublime-Style-Column-Selection 1.7.3 
```

**Comment by 0wnrepo** [comment]
happens to me also on dragging large plantuml.

**Comment by 4umarik** [comment]
Pretty annoying. Happens every time you switch tabs with plantuml view.

**Comment by elJosho** [comment]
happens to me while dragging, but worst is it breaks all Find/Replace functions when the viewer window is up.  The error pops up every time I try to find something and it acts as though nothing happened (no find is performed), as long as the viewer window is visible.

**Comment by bowmanpete123** [comment]
I was building a sequence diagram, and it threw this error when the "newpage" command was used
