### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by tooh** [markushedvall/plantuml-viewer#8]
[Enter steps to reproduce below:]

1. make plantuml diagram
2. goto diagram pane
3. invoke options windows
4. select save as

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [plantuml-viewer](https://github.com/markushedvall/plantuml-viewer) package, v0.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/peter/.atom/packages/plantuml-viewer/lib/plantuml-viewer-view.js:166

TypeError: Cannot read property 'replace' of undefined
  at saveAs (/Users/peter/.atom/packages/plantuml-viewer/lib/plantuml-viewer-view.js:166:36)
  at space-pen-div.<anonymous> (/Users/peter/.atom/packages/plantuml-viewer/lib/plantuml-viewer-view.js:81:7)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:143:19)
  at EventEmitter.module.exports.WindowEventHandler.handleIPCContextCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:219:28)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:140:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:154:31)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:297:31)

```

### Commands

```
 36x -4:01.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  4x -3:34.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:33.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  6x -3:33.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -3:30.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -3:30 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -3:29.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -3:26.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:26.2.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
 25x -3:23.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:09.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:47.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 41x -1:36.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:24.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:24.6.0 set-syntax:PlantUML (atom-text-editor.editor)
  3x -0:45.6.0 core:save-as (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
language-plantuml, v0.1.1
plantuml-viewer, v0.7.0
set-syntax, v0.3.0

# Dev
No dev packages
```

**Comment by tooh** [comment]
Restarted and reopened file. Error does not occur.

**Comment by sgorbyo** [comment]
Restarted and reopened error continues.

**Comment by broussea1901** [comment]
It happens only when the plant UML source file is modified and not saved before exporting preview.
Saved file and error is gone.
